<?php

/**
 * @file
 * Primary module hooks for Dashchart module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */
function dashchart_theme($existing, $type, $theme, $path) {
  return [
    'dashchart_devices' => [
      'variables' => [],
    ],
    'dashchart_brand_stats' => [
      'variables' => [],
    ],
    'dashchart_compatibility' => [
      'variables' => [],
    ],
  ];
}
